### ISSUE TITLE
Switch to streaming files to disk

### ISSUE THREAD

**Issue by JohnGiorgi** [PathwayCommons/pubmed-dl#11]
1. Change `uids_to_docs` to be a generator. This means removing the `return` and sticking a `yield`  inside the for loop (see [here](https://realpython.com/introduction-to-python-generators/)).
2. Move `uids_to_docs` into the for loop in `main.py`. This is what will cause iteration.
3. Test.

**Comment by Anwesh1** [comment]
Hey @JohnGiorgi, so the ```yield``` is working but I need to introduce an error somewhere to see if it will print up that. As of right now, it is printing everything like before, so at least we know it works that far.

**Comment by Anwesh1** [comment]
Building on top of the previous comment. I tried to introduce an unacceptable value but the code is designed to skip it. Is there a way to introduce an error by any chance?
I have the file open when running it and I only see all the data once it has completed running (just like before). So is it really writing by batches of 10000?

**Comment by JohnGiorgi** [comment]
@Anwesh1 look into the `raise` keyword in python, that sounds like what you want

**Comment by Anwesh1** [comment]
@JohnGiorgi just tried that, if there is an exception being raised, the ```yield``` is still not outputting data up till that point. Some other changes might be required, I'm looking into it now

**Comment by JohnGiorgi** [comment]
Up to the point the exception is raised or after it? Might help to open a PR with what you have and provide as much detail about this issue as possible along with a little code snippet I can run to reproduce the error

**Comment by Anwesh1** [comment]
It isn't printing anything (before or after) if it comes across an exception. Have created a PR, you can have a look when free, thanks.
